
-- CUSTOMER_INFO

create database ACCOUNT_INFO
-- CUSTOMER_OERSONAL_INFO

CREATE TABLE Customer_personal_info
(
	CUSTOMER_ID VARCHAR(5) PRIMARY KEY,
	CUSTOMER_NAME VARCHAR(20) NOT NULL,
	DATE_OF_BIRTH DATE NOT NULL,
	GURDIAN_NAME VARCHAR(20) NOT NULL,
	ADDRESS VARCHAR(50) NOT NULL,
	EMAIL_ID VARCHAR(20) NOT NULL,
	GENDER CHAR(1) NOT NULL,
	MARITAL_STATUS VARCHAR(10) NOT NULL,
	IDENTIFICATION_DOC_TYPE VARCHAR(30) NOT NULL,
	CITIZENSHIP VARCHAR(10)NOT NULL
)
SELECT* FROM Customer_personal_info

-- BANK_INFO
  CREATE TABLE Bank_info(
	ISFC_CODE VARCHAR(10) PRIMARY KEY,
	BANK_NAME VARCHAR (20) NOT NULL,
	BRANCH_NAME VARCHAR (25) NOT NULL	  
)
SELECT * FROM Bank_info

--ACCOUNT_INFO
CREATE TABLE Account_info 
(
ACCOUNT_NO BIGINT PRIMARY KEY,
CUSTOMER_ID VARCHAR (5) REFERENCES Customer_personal_info(CUSTOMER_ID),
ACCOUNT_TYPE VARCHAR(10) NOT NULL,
REGISTRATION_DATE DATE,
ACTIVATION_DATE DATE,
ISFC_CODE VARCHAR(10) REFERENCES Bank_info(ISFC_CODE) ,
INTEREST DECIMAL(7,2),
INITIAL_DEPOSIT integer
)
SELECT * FROM Account_info

INSERT INTO Bank_info(ISFC_CODE,BANK_NAME,BRANCH_NAME)VALUES('HDVL0012','HDFC','VALASARVAKKAM')
INSERT INTO Bank_info(ISFC_CODE,BANK_NAME,BRANCH_NAME)VALUES('SBITN0123','SBI','TNAGAR')
INSERT INTO Bank_info(ISFC_CODE,BANK_NAME,BRANCH_NAME)VALUES ('ICITN345','ICICI','TNAGAR')
INSERT INTO Bank_info(ISFC_CODE,BANK_NAME,BRANCH_NAME)VALUES('ICIPG0763','ICICI','PERUNGUDI')
INSERT INTO Bank_info(ISFC_CODE,BANK_NAME,BRANCH_NAME)VALUES('SBISD0122','SBI','SAIDAPET')

SELECT* FROM Bank_info
INSERT INTO Customer_personal_info(CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GURDIAN_NAME,ADDRESS,EMAIL_ID,GENDER,MARITAL_STATUS,IDENTIFICATION_DOC_TYPE,CITIZENSHIP)VALUES('C-001','JHON','2002-03-15','PETER','NO.1,MARIA ROAD','bobby@gmail.com','M','unmaried','idcard_info','INDIAN')
INSERT INTO Customer_personal_info(CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GURDIAN_NAME,ADDRESS,EMAIL_ID,GENDER,MARITAL_STATUS,IDENTIFICATION_DOC_TYPE,CITIZENSHIP)VALUES('C-002','JHONS','2003-03-15','PETERS','NO.1,MAI ROAD','bobbDEVy@gmail.com','M','unmaried','idcard_infoS','INDIAN')
INSERT INTO Customer_personal_info(CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GURDIAN_NAME,ADDRESS,EMAIL_ID,GENDER,MARITAL_STATUS,IDENTIFICATION_DOC_TYPE,CITIZENSHIP)VALUES('C-003','JHONCENA','2004-03-15','ROMAN','NO.1,MAI STREET','JOHNENAy@gmail.com','M','unmaried','idcard_infoS','AMERICAN')
INSERT INTO Customer_personal_info(CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GURDIAN_NAME,ADDRESS,EMAIL_ID,GENDER,MARITAL_STATUS,IDENTIFICATION_DOC_TYPE,CITIZENSHIP)VALUES('C-004','ROMAN','2005-03-15','ROMAN','NO.1,ROMANSTREET','ROMAN@gmail.com','M','married','idcard','AMERICAN')
INSERT INTO Customer_personal_info(CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GURDIAN_NAME,ADDRESS,EMAIL_ID,GENDER,MARITAL_STATUS,IDENTIFICATION_DOC_TYPE,CITIZENSHIP)VALUES('C-005','triplh','2006-03-15','ROMANrgn','NO.1,MAkliSTREET','tripleh@gmail.com','M','unmaried','varification_card','AMERICAN')
INSERT INTO Customer_personal_info(CUSTOMER_ID,CUSTOMER_NAME,DATE_OF_BIRTH,GURDIAN_NAME,ADDRESS,EMAIL_ID,GENDER,MARITAL_STATUS,IDENTIFICATION_DOC_TYPE,CITIZENSHIP)VALUES('C-006','kan','2007-03-15','ROCK','NO.1,MAkliSTREET','KAN@gmail.com','M','married','varification_card','INDIAN')
			 		 		  			
SELECT* FROM Customer_personal_info		

INSERT INTO Account_info(ACCOUNT_NO,CUSTOMER_ID,ACCOUNT_TYPE,REGISTRATION_DATE,ACTIVATION_DATE,ISFC_CODE,INTEREST,INITIAL_DEPOSIT)VALUES('24578758867','C-001','CURRENT','2002-08-09','2003-09-08','SBITN0123',67.03,2578)
INSERT INTO Account_info(ACCOUNT_NO,CUSTOMER_ID,ACCOUNT_TYPE,REGISTRATION_DATE,ACTIVATION_DATE,ISFC_CODE,INTEREST,INITIAL_DEPOSIT)VALUES('24578758869','C-002','CURRENT','2002-08-08','2003-06-08','ICITN345',56.89,3000)
INSERT INTO Account_info(ACCOUNT_NO,CUSTOMER_ID,ACCOUNT_TYPE,REGISTRATION_DATE,ACTIVATION_DATE,ISFC_CODE,INTEREST,INITIAL_DEPOSIT)VALUES('84578758869','C-005','SAVING','2007-08-08','2009-06-08','SBISD0122',78.69,5000)
INSERT INTO Account_info(ACCOUNT_NO,CUSTOMER_ID,ACCOUNT_TYPE,REGISTRATION_DATE,ACTIVATION_DATE,ISFC_CODE,INTEREST,INITIAL_DEPOSIT)VALUES('84578758868','C-003','SAVING','2007-08-09',NULL,'SBISD0122',7.69,9000)
					
SELECT* FROM Account_info	
UPDATE Account_info
SET ACTIVATION_DATE = '2003-02-02'

UPDATE Account_info 
SET ACTIVATION_DATE = '2002-03-15'
WHERE CUSTOMER_ID= 'C-003'

ALTER TABLE Customer_personal_info
RENAME TO CUSTOMER_PERSONAL_IFO

ALTER TABLE Bank_info
RENAME TO BANK_IFO

ALTER TABLE BANK_IFO
ADD COLUMN BANK_CODE INTEGER UNIQUE
ALTER TABLE BANK_IFO
DROP COLUMN BANK_CODE
 
SELECT ACCOUNT_NO AS AC_NO,ACCOUNT_TYPE AS AC_TYPE 
FROM Account_info
  -- count the total rows
 SELECT COUNT(*)FROM Account_info
 -- DISTINCT will give you a unique value 
 --regardless of that  Account_info table consist of all unique data that's why showing same as count
SELECT DISTINCT(COUNT(*))FROM Account_info
-- SORT BY CUSTOMER_NAME VALUE
SELECT * FROM CUSTOMER_PERSONAL_IFO
ORDER BY CUSTOMER_NAME

-- %WILDCARD%

SELECT CUSTOMER_NAME FROM CUSTOMER_PERSONAL_IFO 
WHERE CUSTOMER_NAME LIKE 'J%'
 
SELECT ACCOUNT_TYPE FROM  Account_info 
WHERE ACCOUNT_TYPE LIKE '%T' 

SELECT ACCOUNT_TYPE FROM Account_info
WHERE  ACCOUNT_TYPE LIKE '_URR%'
ORDER BY REGISTRATION_DATE

 --JOINS
 SELECT * FROM Account_info
 
 SELECT ACTIVATION_DATE,REGISTRATION_DATE
 FROM Account_info
 INNER JOIN CUSTOMER_PERSONAL_IFO
 ON CUSTOMER_PERSONAL_IFO.CUSTOMER_ID  = Account_info.CUSTOMER_ID

 
  
 SELECT ACTIVATION_DATE,REGISTRATION_DATE
 FROM Account_info
 RIGHT JOIN CUSTOMER_PERSONAL_IFO
 ON CUSTOMER_PERSONAL_IFO.CUSTOMER_ID  = Account_info.CUSTOMER_ID
 
  
 SELECT ACTIVATION_DATE,REGISTRATION_DATE
 FROM Account_info
 LEFT JOIN CUSTOMER_PERSONAL_IFO
 ON CUSTOMER_PERSONAL_IFO.CUSTOMER_ID  = Account_info.CUSTOMER_ID
 
 
SELECT CUSTOMER_ID AS ID_VAR FROM CUSTOMER_PERSONAL_IFO
UNION
SELECT ISFC_CODE FROM BANK_IFO
UNION
SELECT CUSTOMER_ID AS ACC_ID FROM Account_info 

